Fix menuItem unloading
hannesdelbeke/maya-plugin-template pull request #4
Opened 2024-01-11 10:58 UTC by ElgoogUdiab

When MAYA create the menuItem, it will generate a unique name for it. This name should be used when deleting the menu item instead of its label.

2024-01-11 11:14 UTC, hannesdelbeke commented on my_plugin.py
> +MENU_ENTRY_NAME = "" # Store generated menu item, used when unregister
looks good, only thing left is to change `MENU_ENTRY_NAME` to `__menu_entry_name` since it's a private variable, not a constant

2024-01-11 11:16 UTC, hannesdelbeke commented on my_plugin.py
>          cmds.menu(MENU_NAME, label=MENU_LABEL, parent=MENU_PARENT)
we make a menu here, might want to do the same here `__menu_entry = ...`

2024-01-11 12:55 UTC, ElgoogUdiab commented
Done. `MENU_ENTRY_NAME` is now renamed to `__menu_entry_name`.

2024-01-11 13:05 UTC, hannesdelbeke requested changes

2024-01-11 13:05 UTC, hannesdelbeke commented on my_plugin.py
> +__meun_entry_name = "" # Store generated menu item, used when unregister
typo

2024-01-11 15:01 UTC, hannesdelbeke approved these changes

2024-01-11 15:01 UTC, merged

2024-01-16 09:59 UTC, ElgoogUdiab commented
resolves #1